### ISSUE TITLE
链表

### ISSUE THREAD

**Issue by zhangzhangbang** [Alephant6/zywPython#10]
![image](https://user-images.githubusercontent.com/95964910/169436286-d8301e52-8f27-40c4-a2e7-39b8ef398179.png)
我觉得写挺好的为啥报错

**Comment by Alephant6** [comment]
对照伪代码看看呢，是不是一致的？

**Comment by zhangzhangbang** [comment]
![image](https://user-images.githubusercontent.com/95964910/169436895-b207c858-a861-4549-8375-30905d0edd7f.png)
是一模一样的

**Comment by Alephant6** [comment]
while语句那一行不一样

**Comment by zhangzhangbang** [comment]
ooo搞定了

**Comment by Alephant6** [comment]
ok, then this issue can be closed
