### ISSUE TITLE
链表

### ISSUE THREAD

**Issue by zhangzhangbang** [Alephant6/zywPython#11]
![image](https://user-images.githubusercontent.com/95964910/169442445-ed5b1376-060f-4564-81a6-313aafa72c79.png)
我想jian'c检验一下自己真会了没又自己重新做了另一个链表题  我不理解我的做法为啥不对

**Comment by Alephant6** [comment]
1. 自己画一个图用自己的代码一步一步，比划一下
2. 标题里加一下力扣第几题呗，方便后期回顾

**Comment by zhangzhangbang** [comment]
![IMG_20220520_113033_edit_28592401120115](https://user-images.githubusercontent.com/95964910/169445639-97aed052-fdc7-47c0-9944-f84ea0b1176a.jpg)
遍历到最后有点小问题，我想知道如果解决了最后那个head.next为空这个问题 我写的这段代码有啥逻辑上的错误吗

**Comment by zhangzhangbang** [comment]
![image](https://user-images.githubusercontent.com/95964910/169446685-432ef9bf-9657-4714-82f4-d813d633dd78.png)
不错 这回链表真的学的透透的了
