### ISSUE TITLE
⻬普夫定律（Zipf’s law）

### ISSUE THREAD

**Issue by Alephant6** [Alephant6/zywPython#24]
@zhangzhangbang 

![image](https://user-images.githubusercontent.com/53031172/172873385-5d98b39f-0b2a-4391-938f-3c27f377f274.png)

[《d2l-zh-pytorch》p304](https://github.com/Alephant6/zywPython/blob/main/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/d2l-zh-pytorch.pdf)

**Comment by Frankbluemoon** [comment]
该定律指出文章中单词的频次(f)与其排列的序号(r)之间存在着下述定量的关系，齐普夫认为：如果有一个包含n 个词的文章，将这些词按其出现的频次递减地排序，那么序号r和其出现频次f之积fr，将近似地为一个常数，即fr=b，(式中r=1,2,3.…)，即词频分布定律最普通而又最典型的表达。

**Comment by Frankbluemoon** [comment]
Frankbluemoon
