### ISSUE TITLE
5.19 栈

### ISSUE THREAD

**Issue by zhangzhangbang** [Alephant6/zywPython#8]
![image](https://user-images.githubusercontent.com/95964910/169260417-b0c98d20-44e4-45f0-b073-60d81f6c4296.png)
为啥这里不能用if判断，我觉得while和if的用法好难区分啊

**Comment by zhangzhangbang** [comment]
这里的运行顺序是不是k+1之后直接就到下一个if语句了？

**Comment by Alephant6** [comment]
> ![image](https://user-images.githubusercontent.com/95964910/169260417-b0c98d20-44e4-45f0-b073-60d81f6c4296.png)
> 
> 为啥这里不能用if判断，我觉得while和if的用法好难区分啊
> 
> 我觉得while语句可以看作是if➕for

先判断是否满足条件，然后循环执行

**Comment by Alephant6** [comment]
> 这里的运行顺序是不是k+1之后直接就到下一个if语句了？

是的

**Comment by zhangzhangbang** [comment]
我的意思是他只运行一遍k+1不会再回去判断k<n and nums2[k]..... 这样也是直接到下一个if吗

**Comment by Alephant6** [comment]
不会，他执行过if内的语句块后，不会再回头执行if；会回头的是while
